project:
  type: website

website:
  title: "Reut Shachnai"
  search: false
  navbar:
    right:
      - href: "#research"
        text: Research Interests
      - href: "#publications"
        text: Publications
      - href: "#press"
        text: Press
      - href: "#cv"
        text: CV
      - href: "#contact"
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false