project:
  type: website
  output-dir: docs

website:
  title: "Reut Shachnai"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: press.qmd
        text: Press
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false